# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '/home/vsts/work/1/s/target/DinnerOrder-1.0.war'
    ArtifactName: 'dinner-order'
    publishLocation: 'Container'

- task: sftpupload@1
  inputs:
    sourceFolder: '/home/vsts/work/1/s/target/'
    contents: 'DinnerOrder-1.0.war'
    targetFolder: '/opt/apache-tomcat-10.1.13/webapps/'
    host: '47.91.41.9'
    port: '22'
    username: 'root'
    password: 'Sydney123'